# Generated by Django 5.1.3 on 2026-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('hp', models.PositiveIntegerField(verbose_name='Horse Power')),
                ('engine_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=50)),
                ('number_plate', models.CharField(max_length=10, unique=True, verbose_name='Number Plate')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN Number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Car',
            },
        ),
    ]
